pdfjsLib.GlobalWorkerOptions.workerSrc = "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js";

const sources = {};
const libraryItemsMap = {};
let libraryOrder = [];
let libPageCounter = 0;
let pages = [];
let idCounter = 0;
let sourceCounter = 0;
let selectedIds = new Set();
let selectedLibIds = new Set();
let selectedLibSectionIds = new Set();
let trash = [];
let trashCounter = 0;
let currentDrag = null;

// ── Secciones ──
let sections = [];            // Secciones del lienzo: { id, name, pageIds: [] }
let librarySections = [];     // Secciones de biblioteca: { id, name, libIds: [] }
let sectionCounter = 0;       // Contador para secciones del lienzo (secN)
let libSectionCounter = 0;    // Contador para secciones de biblioteca (libsecN)
let undoState = null;         // { scope:'canvas'|'library', sectionId, created }
let undoTimeout = null;       // Temporizador de 20s para deshacer

const dropScreen = document.getElementById('dropScreen');
const dropZone = document.getElementById('dropZone');
const fileInput = document.getElementById('fileInput');
const addMoreInput = document.getElementById('addMoreInput');
const workspace = document.getElementById('workspace');
const libraryPanel = document.getElementById('libraryPanel');
const libraryList = document.getElementById('libraryList');
const libraryEmpty = document.getElementById('libraryEmpty');
const libSelectAllBtn = document.getElementById('libSelectAllBtn');
const libSelectionBar = document.getElementById('libSelectionBar');
const libSelCount = document.getElementById('libSelCount');
const libDeleteSelectedBtn = document.getElementById('libDeleteSelectedBtn');
const libCancelSelectionBtn = document.getElementById('libCancelSelectionBtn');
const pageList = document.getElementById('pageList');
const canvasArea = document.getElementById('canvasArea');
const emptyState = document.getElementById('emptyState');
const pageCountEl = document.getElementById('pageCount');
const pageCountInput = document.getElementById('pageCountInput');
const pageCountTotal = document.getElementById('pageCountTotal');
const selectAllBtn = document.getElementById('selectAllBtn');
const exportBtn = document.getElementById('exportBtn');
const toast = document.getElementById('toast');
const toastMsg = document.getElementById('toastMsg');
const zoomSlider = document.getElementById('zoomSlider');
const zoomPct = document.getElementById('zoomPct');
const selectionBar = document.getElementById('selectionBar');
const selCount = document.getElementById('selCount');
const sendToLibraryBtn = document.getElementById('sendToLibraryBtn');
const deleteSelectedBtn = document.getElementById('deleteSelectedBtn');
const cancelSelectionBtn = document.getElementById('cancelSelectionBtn');
const trashBtn = document.getElementById('trashBtn');
const trashBadge = document.getElementById('trashBadge');
const trashPanel = document.getElementById('trashPanel');
const trashList = document.getElementById('trashList');
const trashEmpty = document.getElementById('trashEmpty');
const closeTrashBtn = document.getElementById('closeTrashBtn');
const clearTrashBtn = document.getElementById('clearTrashBtn');
const confirmModal = document.getElementById('confirmModal');
const confirmMsg = document.getElementById('confirmMsg');
const confirmOk = document.getElementById('confirmOk');
const confirmCancel = document.getElementById('confirmCancel');
const sectionKeepModal = document.getElementById('sectionKeepModal');
const sectionKeepMsg = document.getElementById('sectionKeepMsg');
const sectionKeepNoBtn = document.getElementById('sectionKeepNoBtn');
const sectionKeepYesBtn = document.getElementById('sectionKeepYesBtn');
const lightbox = document.getElementById('lightbox');
const lightboxStage = document.getElementById('lightboxStage');
const lightboxImg = document.getElementById('lightboxImg');
const lightboxClose = document.getElementById('lightboxClose');
const lbZoomLevel = document.getElementById('lbZoomLevel');
const lbZoomOut = document.getElementById('lbZoomOut');
const lbZoomIn = document.getElementById('lbZoomIn');
const lbFit = document.getElementById('lbFit');
const lbPageInput = document.getElementById('lbPageInput');
const lbPageTotal = document.getElementById('lbPageTotal');
const lbPrev = document.getElementById('lbPrev');
const lbNext = document.getElementById('lbNext');
